apiVersion: v1 
kind: Pod 
metadata:
  name: kuard 
spec:
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:blue
      name: kuard 
      resources:
        requests:  #request for resources
          #The Pod will not be scheduled on a node that does not have at least these resources available
          cpu: "500m"   #500 milliCPU, or half a CPU core
          memory: "128Mi" #128 MiB of memory
      ports:
        - containerPort: 8080
          name: http 
          protocol: TCP