apiVersion: v1
kind: Service
metadata:
  name: legacy-mysql      # Internal name
spec:
  ports:
    - port: 3306            # Service port
      targetPort: 3306        # External resource port
  # NO selector here! (This is key)